### ISSUE TITLE
登录成功,返回的TOKEN为:{"error":"invalid_client"}

### ISSUE THREAD

**Issue by bestoml** [nwcdlabs/iot-mobile-control-using-cognito#1]
按照教程操作后,注册成功,会看到USER POOL中已经出现了新USER,但是登录回到主界面后,发现返回的
TOKEN为:{"error":"invalid_client"};

**Comment by salander0411** [comment]
invalid_client 是验证失败导致的，检查你的 client id 以及配置细节。比如 cognito app client那里，是要取消 generate client secret 的这个选项的。

**Comment by bestoml** [comment]
看到了,我的确有设置client secret ,谢谢.
