### ISSUE TITLE
最终控制上,并没有体现把帐号与Thing对应起来.

### ISSUE THREAD

**Issue by bestoml** [nwcdlabs/iot-mobile-control-using-cognito#2]
比如我现在在IOT上有THING T1,T2,T3;在 User Pool上有用户A;我的目的是用户A,绑定设备T1,T2;
是否是这样理解:
比如T1,在IOT上正常工作后,他发送的TOPIC是: /T1NAME/XXXXX;
用户绑定T1,其实就是把用户A与 T1NAME绑定,这时用户A 定阅的是 /T1NAME/的TOPIC,这样就表示两者绑定在一起了?
而T1NAME就是设备出厂时通过二维码之类的方式让用户输入?

**Comment by salander0411** [comment]
大概流程是这样没错。补充一点，绑定的过程其实也是授权的过程，IAM会控制权限。也就是说，如果T4这台设备不属于你，即使你知道了那个topic的路径名称是/T4NAME/，也是无法交互的。

**Comment by bestoml** [comment]
明白,谢谢.
